# Generated by Django 5.1 on 2024-08-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosmatics', '0001_initial'),
        ('public_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='')),
                ('response', models.TextField(default='')),
                ('status', models.IntegerField(default=0, null=True)),
                ('rid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='public_management.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='cosmatics.cosmetics')),
                ('rid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='public_management.registration')),
                ('saloon_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saloon_feedbacks', to='public_management.registration')),
            ],
        ),
    ]
