# Generated by Django 5.1 on 2024-08-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosmatics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=20, null=True)),
                ('cvv', models.CharField(blank=True, max_length=10, null=True)),
                ('valid_date', models.CharField(max_length=6, null=True)),
                ('booking_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('booking_time', models.TimeField(null=True)),
                ('messages', models.TextField(blank=True)),
                ('payment', models.CharField(default='null', max_length=50)),
                ('status', models.CharField(default='not given', max_length=50, null=True)),
                ('no_of_products', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_products', models.PositiveIntegerField(default=0)),
                ('cosmetic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmatics.cosmetics')),
            ],
        ),
    ]
