# Generated by Django 5.1 on 2024-08-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('cosmatics', '0001_initial'),
        ('feedback', '0002_initial'),
        ('product', '0001_initial'),
        ('public_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_management.registration'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='cosmetic_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmatics.cosmetics'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacks'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_management.registration'),
        ),
    ]
