# Generated by Django 5.1 on 2024-08-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('public_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(default='', max_length=200)),
                ('number_of_products', models.IntegerField(default=0)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_management.registration')),
            ],
        ),
    ]
